-- MANAGED_CONTENT
CREATE TABLE MANAGED_CONTENT ( 
  ID     INTEGER         NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
  CSS    VARCHAR (4000),
  SCRIPT VARCHAR (4000)
);
ALTER TABLE MANAGED_CONTENT ADD CONSTRAINT MANA_CONT_PK PRIMARY KEY (ID);

-- CONTENT_TYPE
CREATE TABLE CONTENT_TYPE (
  ID   INTEGER      NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CD   VARCHAR (15) NOT NULL,
  NAME VARCHAR (50) NOT NULL
);
ALTER TABLE CONTENT_TYPE ADD CONSTRAINT CONT_TYPE_PK PRIMARY KEY (ID);
ALTER TABLE CONTENT_TYPE ADD CONSTRAINT CONT_TYPE_UK_1 UNIQUE (CD);

-- CONTENT
CREATE TABLE CONTENT (
  ID                 INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CONTENT_TYPE_ID    INTEGER       NOT NULL,
  MANAGED_CONTENT_ID INTEGER       NOT NULL,
  ORDER_NO           INTEGER       NOT NULL,
  DESCRIPTION        VARCHAR (100) NOT NULL,
  TEXT               VARCHAR (4000),
  MEDIA              BLOB,
  MEDIA_CONTENT_TYPE VARCHAR (100), 
  LINK               VARCHAR (500),
  LINK_TARGET        VARCHAR (15)
);
ALTER TABLE CONTENT ADD CONSTRAINT CONT_PK PRIMARY KEY (ID);
ALTER TABLE CONTENT ADD CONSTRAINT CONT_UK_1 UNIQUE (MANAGED_CONTENT_ID, ORDER_NO);
ALTER TABLE CONTENT ADD CONSTRAINT CONT_CONT_TYPE_FK_1 FOREIGN KEY (CONTENT_TYPE_ID) REFERENCES CONTENT_TYPE (ID);
ALTER TABLE CONTENT ADD CONSTRAINT CONT_MANA_CONT_FK_1 FOREIGN KEY (MANAGED_CONTENT_ID) REFERENCES MANAGED_CONTENT (ID);
