-- CUSTOMER
CREATE TABLE CUSTOMER ( 
  ID          INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  NAME        VARCHAR (100) NOT NULL, 
  DESCRIPTION VARCHAR (500), 
  ADDRESS_ID  INTEGER 
);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUST_PK PRIMARY KEY (ID);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUST_ADDR_FK_1 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID);

-- AD
CREATE TABLE AD ( 
  ID                 INTEGER   NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
  STATUS             INTEGER   NOT NULL, 
  CUSTOMER_ID        INTEGER   NOT NULL, 
  DESCRIPTION        VARCHAR (500), 
  ARTICLE_ID         INTEGER, 
  MANAGED_CONTENT_ID INTEGER   NOT NULL, 
  VALID_FROM         TIMESTAMP NOT NULL, 
  VALID_TO           TIMESTAMP
);
ALTER TABLE AD ADD CONSTRAINT AD_PK PRIMARY KEY (ID) ;
ALTER TABLE AD ADD CONSTRAINT AD_CK_1 CHECK (STATUS IN (0,1));
ALTER TABLE AD ADD CONSTRAINT AD_CUST_FK_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID);
ALTER TABLE AD ADD CONSTRAINT AD_ARTI_FK_1 FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ID);
ALTER TABLE AD ADD CONSTRAINT AD_MANA_CONT_FK_1 FOREIGN KEY (MANAGED_CONTENT_ID) REFERENCES MANAGED_CONTENT (ID);


