-- ROLES
INSERT INTO ROLES (CD, NAME) VALUES ('VISITOR', 'Visitor');
INSERT INTO ROLES (CD, NAME) VALUES ('CONTRIBUTOR', 'Contributor');
INSERT INTO ROLES (CD, NAME) VALUES ('DESIGNER', 'Designer');
INSERT INTO ROLES (CD, NAME) VALUES ('EDITOR', 'Editor');
INSERT INTO ROLES (CD, NAME) VALUES ('ADMINISTRATOR', 'Administrator');

-- COUNTRY
INSERT INTO COUNTRY (CD, NAME) VALUES ('RS', 'Srbija');
