-- ROLES
INSERT INTO ROLES (CD, NAME) VALUES ('VISITOR', 'Visitor');
INSERT INTO ROLES (CD, NAME) VALUES ('CONTRIBUTOR', 'Contributor');
INSERT INTO ROLES (CD, NAME) VALUES ('DESIGNER', 'Designer');
INSERT INTO ROLES (CD, NAME) VALUES ('EDITOR', 'Editor');
INSERT INTO ROLES (CD, NAME) VALUES ('ADMINISTRATOR', 'Administrator');

-- USER_STATUS
INSERT INTO USER_STATUS (CD, NAME) VALUES ('0', 'Inactive');
INSERT INTO USER_STATUS (CD, NAME) VALUES ('1', 'Active');

-- COUNTRY
INSERT INTO COUNTRY (CD, NAME) VALUES ('RS', 'Serbia');

-- USERS
INSERT INTO USERS (
  USER_NAME,
  PASSWORD,
  STATUS_ID,
  ROLE_ID
) VALUES (
  'admin',
  '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918',
  (SELECT ID FROM USER_STATUS WHERE CD = '1'),
  (SELECT ID FROM ROLES WHERE CD = 'ADMINISTRATOR')
);
