-- ROLES
INSERT INTO ROLES (CD, NAME) VALUES ('VISITOR', 'Visitor');
INSERT INTO ROLES (CD, NAME) VALUES ('CONTRIBUTOR', 'Contributor');
INSERT INTO ROLES (CD, NAME) VALUES ('DESIGNER', 'Designer');
INSERT INTO ROLES (CD, NAME) VALUES ('EDITOR', 'Editor');
INSERT INTO ROLES (CD, NAME) VALUES ('ADMINISTRATOR', 'Administrator');

-- USER_STATUS
INSERT INTO USER_STATUS (CD, NAME) VALUES ('0', 'Inactive');
INSERT INTO USER_STATUS (CD, NAME) VALUES ('1', 'Active');

-- COUNTRY
INSERT INTO COUNTRY (CD, NAME) VALUES ('RS', 'Serbia');
