-- SYSTEM
-- ROLES
INSERT INTO ROLES (CD, NAME) VALUES ('administrator', 'Administrator');
INSERT INTO ROLES (CD, NAME) VALUES ('editor', 'Urednik');
INSERT INTO ROLES (CD, NAME) VALUES ('journalist', 'Novinar');
INSERT INTO ROLES (CD, NAME) VALUES ('visitor', 'Posetilac');
 
-- USER_STATUS
INSERT INTO USER_STATUS (CD, NAME) VALUES ('active', 'Aktivan');
INSERT INTO USER_STATUS (CD, NAME) VALUES ('inactive', 'Neaktivan');

-- USERS
INSERT INTO USERS (
  USER_NAME,
  PASSWORD,
  FIRST_NAME,
  LAST_NAME,
  STATUS_ID,
  ROLE_ID
) VALUES (
  'idugic@gmail.com',
  '21893ed8828f762a0d93c4e98b877857', -- admin (md5)
  'Ivan',
  'Dugić',
  (SELECT ID FROM USER_STATUS WHERE CD = 'active'),
  (SELECT ID FROM ROLES WHERE CD = 'administrator')
);

-- COUNTRY
INSERT INTO COUNTRY (CD, NAME) VALUES ('rs', 'Srbija');

-- PROJECT MANAGEMENT
-- TASK_STATUS
INSERT INTO TASK_STATUS (CD, NAME) VALUES ('new', 'New');
INSERT INTO TASK_STATUS (CD, NAME) VALUES ('completed', 'Completed');
INSERT INTO TASK_STATUS (CD, NAME) VALUES ('deleted', 'Deleted');

-- TASK_PRIORITY
INSERT INTO TASK_PRIORITY (CD, NAME) VALUES ('normal', 'Normal');
INSERT INTO TASK_PRIORITY (CD, NAME) VALUES ('high', 'High');
INSERT INTO TASK_PRIORITY (CD, NAME) VALUES ('low', 'Low');

-- CONTENT MANAGEMENT
INSERT INTO CONTENT_TYPE (CD, NAME) VALUES ('text', 'Text');
INSERT INTO CONTENT_TYPE (CD, NAME) VALUES ('media', 'Media');

-- MAGAZINE
-- READER_TYPE
INSERT INTO READER_TYPE (CD, NAME) VALUES ('kids', 'Kids (Ages 7-14)');

-- ARTICLE_STATUS
INSERT INTO ARTICLE_STATUS (CD, NAME) VALUES ('new', 'New');
INSERT INTO ARTICLE_STATUS (CD, NAME) VALUES ('design', 'In Design');
INSERT INTO ARTICLE_STATUS (CD, NAME) VALUES ('ready', 'Ready to be Published');
INSERT INTO ARTICLE_STATUS (CD, NAME) VALUES ('published', 'Published');
INSERT INTO ARTICLE_STATUS (CD, NAME) VALUES ('deleted', 'Deleted');

-- ARTICLE_COMMENT_STATUS
INSERT INTO ARTICLE_COMMENT_STATUS (CD, NAME) VALUES ('new', 'New');
INSERT INTO ARTICLE_COMMENT_STATUS (CD, NAME) VALUES ('accepted', 'Accepted');
INSERT INTO ARTICLE_COMMENT_STATUS (CD, NAME) VALUES ('reject', 'Rejected');
INSERT INTO ARTICLE_COMMENT_STATUS (CD, NAME) VALUES ('archived', 'Archived');

-- MARKETING
-- AD_STATUS
INSERT INTO AD_STATUS (CD, NAME) VALUES ('new', 'New');
INSERT INTO AD_STATUS (CD, NAME) VALUES ('design', 'In Design');
INSERT INTO AD_STATUS (CD, NAME) VALUES ('ready', 'Ready to be Published');
INSERT INTO AD_STATUS (CD, NAME) VALUES ('published', 'Published');
INSERT INTO AD_STATUS (CD, NAME) VALUES ('deleted', 'Deleted');

