-- SYSTEM
-- ROLES
INSERT INTO ROLES (CD, NAME) VALUES ('administrator', 'Administrator');
INSERT INTO ROLES (CD, NAME) VALUES ('editor-00', 'Editor in Chief');
INSERT INTO ROLES (CD, NAME) VALUES ('editor-01', 'Associate Editor');
INSERT INTO ROLES (CD, NAME) VALUES ('visitor', 'Visitor');

-- USER_STATUS
INSERT INTO USER_STATUS (CD, NAME) VALUES ('active', 'Active');
INSERT INTO USER_STATUS (CD, NAME) VALUES ('inactive', 'Inactive');

-- COUNTRY
INSERT INTO COUNTRY (CD, NAME) VALUES ('rs', 'Srbija');

-- USERS
INSERT INTO USERS (
  USER_NAME,
  PASSWORD,
  STATUS_ID,
  ROLE_ID
) VALUES (
  'admin',
  '21893ed8828f762a0d93c4e98b877857', -- admin (md5)
  (SELECT ID FROM USER_STATUS WHERE CD = 'active'),
  (SELECT ID FROM ROLES WHERE CD = 'administrator')
);

-- USERS
INSERT INTO USERS (
  USER_NAME,
  PASSWORD,
  STATUS_ID,
  ROLE_ID
) VALUES (
  'editor',
  '1e624427b1feb296a3974e82d19c5ac2', -- editor (md5)
  (SELECT ID FROM USER_STATUS WHERE CD = 'active'),
  (SELECT ID FROM ROLES WHERE CD = 'editor-00')
);

-- USERS
INSERT INTO USERS (
  USER_NAME,
  PASSWORD,
  STATUS_ID,
  ROLE_ID
) VALUES (
  'associate',
  '2cfa2d89ef465d5463b96a34ff1030d6', -- associate (md5)
  (SELECT ID FROM USER_STATUS WHERE CD = 'active'),
  (SELECT ID FROM ROLES WHERE CD = 'editor-01')
);

-- USERS
INSERT INTO USERS (
  USER_NAME,
  PASSWORD,
  STATUS_ID,
  ROLE_ID
) VALUES (
  'visitor',
  '24d36ccee928073eb9f673c0635e9f34', -- visitor (md5)
  (SELECT ID FROM USER_STATUS WHERE CD = 'active'),
  (SELECT ID FROM ROLES WHERE CD = 'visitor')
);

-- PROJECT MANAGEMENT
-- TASK_STATUS
INSERT INTO TASK_STATUS (CD, NAME) VALUES ('new', 'New');
INSERT INTO TASK_STATUS (CD, NAME) VALUES ('completed', 'Completed');
INSERT INTO TASK_STATUS (CD, NAME) VALUES ('deleted', 'Deleted');

-- TASK_PRIORITY
INSERT INTO TASK_PRIORITY (CD, NAME) VALUES ('normal', 'Normal');
INSERT INTO TASK_PRIORITY (CD, NAME) VALUES ('high', 'High');
INSERT INTO TASK_PRIORITY (CD, NAME) VALUES ('low', 'Low');

-- CONTENT MANAGEMENT
INSERT INTO CONTENT_TYPE (CD, NAME) VALUES ('text', 'Text');
INSERT INTO CONTENT_TYPE (CD, NAME) VALUES ('media', 'Media');

-- MAGAZINE
-- READER_TYPE
INSERT INTO READER_TYPE (CD, NAME) VALUES ('kids', 'Kids (Ages 7-14)');

-- ARTICLE_STATUS
INSERT INTO ARTICLE_STATUS (CD, NAME) VALUES ('new', 'New');
INSERT INTO ARTICLE_STATUS (CD, NAME) VALUES ('ready', 'Ready to be Published');
INSERT INTO ARTICLE_STATUS (CD, NAME) VALUES ('published', 'Published');
INSERT INTO ARTICLE_STATUS (CD, NAME) VALUES ('deleted', 'Deleted');

-- ARTICLE_COMMENT_STATUS
INSERT INTO ARTICLE_COMMENT_STATUS (CD, NAME) VALUES ('new', 'New');
INSERT INTO ARTICLE_COMMENT_STATUS (CD, NAME) VALUES ('published', 'Published');
INSERT INTO ARTICLE_COMMENT_STATUS (CD, NAME) VALUES ('deleted', 'Deleted');

-- USER_ARTICLE_STATUS
INSERT INTO USER_ARTICLE_STATUS (CD, NAME) VALUES ('new', 'New');
INSERT INTO USER_ARTICLE_STATUS (CD, NAME) VALUES ('transferred', 'Transferred');
INSERT INTO USER_ARTICLE_STATUS (CD, NAME) VALUES ('deleted', 'Deleted');

-- AD_STATUS
INSERT INTO AD_STATUS (CD, NAME) VALUES ('new', 'New');
INSERT INTO AD_STATUS (CD, NAME) VALUES ('ready', 'Ready to be Published');
INSERT INTO AD_STATUS (CD, NAME) VALUES ('published', 'Published');
INSERT INTO AD_STATUS (CD, NAME) VALUES ('deleted', 'Deleted');

