-- USER_ARTICLE_STATUS
CREATE TABLE USER_ARTICLE_STATUS ( 
  ID   INTEGER      NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
  CD   VARCHAR (15) NOT NULL, 
  NAME VARCHAR (50) NOT NULL 
);
ALTER TABLE USER_ARTICLE_STATUS ADD CONSTRAINT USER_ARTI_STAT_PK PRIMARY KEY (ID);
ALTER TABLE USER_ARTICLE_STATUS ADD CONSTRAINT USER_ARTI_STAT_UK_1 UNIQUE (CD);

-- USER_ARTICLE
CREATE TABLE USER_ARTICLE (
  ID                 INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  STATUS_ID          INTEGER        NOT NULL, 
  TITLE              VARCHAR (200)  NOT NULL, 
  TEXT               VARCHAR (4000), 
  MEDIA              BLOB, 
  MEDIA_CONTENT_TYPE VARCHAR (100),
  UC                 INTEGER        NOT NULL,
  DC                 TIMESTAMP      NOT NULL,
  UM                 INTEGER,
  DM                 TIMESTAMP
);
ALTER TABLE USER_ARTICLE ADD CONSTRAINT USER_ARTI_PK PRIMARY KEY (ID);
ALTER TABLE USER_ARTICLE ADD CONSTRAINT USER_ARTI_USER_ARTI_STAT_FK_1 FOREIGN KEY (STATUS_ID) REFERENCES USER_ARTICLE_STATUS (ID);
ALTER TABLE USER_ARTICLE ADD CONSTRAINT USER_ARTI_USER_FK_1 FOREIGN KEY (UC) REFERENCES USERS (ID);
ALTER TABLE USER_ARTICLE ADD CONSTRAINT USER_ARTI_USER_FK_2 FOREIGN KEY (UM) REFERENCES USERS (ID);

-- ARTICLE_RATE
 CREATE TABLE ARTICLE_RATE (
  ID         INTEGER   NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ARTICLE_ID INTEGER   NOT NULL,
  RATE       INTEGER   NOT NULL,
  UC         INTEGER   NOT NULL,
  DC         TIMESTAMP NOT NULL,
  UM         INTEGER,
  DM         TIMESTAMP
);
ALTER TABLE ARTICLE_RATE ADD CONSTRAINT ARTI_RATE_PK PRIMARY KEY (ID);
ALTER TABLE ARTICLE_RATE ADD CONSTRAINT ARTI_RATE_CK_1 CHECK (RATE IN(1,2,3));
ALTER TABLE ARTICLE_RATE ADD CONSTRAINT ARTI_RATE_ARTI_FK_1 FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ID);
ALTER TABLE ARTICLE_RATE ADD CONSTRAINT ARTI_RATE_USER_FK_1 FOREIGN KEY (UC) REFERENCES USERS (ID);
ALTER TABLE ARTICLE_RATE ADD CONSTRAINT ARTI_RATE_USER_FK_2 FOREIGN KEY (UM) REFERENCES USERS (ID);

-- ARTICLE_COMMENT_STATUS
CREATE TABLE ARTICLE_COMMENT_STATUS ( 
  ID   INTEGER      NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
  CD   VARCHAR (15) NOT NULL, 
  NAME VARCHAR (50) NOT NULL 
);
ALTER TABLE ARTICLE_COMMENT_STATUS ADD CONSTRAINT ARTI_COMM_STAT_PK PRIMARY KEY (ID);
ALTER TABLE ARTICLE_COMMENT_STATUS ADD CONSTRAINT ARTI_COMM_STAT_UK_1 UNIQUE (CD);

-- ARTICLE_COMMENT
CREATE TABLE ARTICLE_COMMENT (
  ID           INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ARTICLE_ID   INTEGER       NOT NULL,
  STATUS_ID    INTEGER       NOT NULL,
  TEXT         VARCHAR (250) NOT NULL,
  PUBLISHED_BY INTEGER,
  PUBLISHED_AT TIMESTAMP,
  UC           INTEGER       NOT NULL,
  DC           TIMESTAMP     NOT NULL,
  UM           INTEGER,
  DM           TIMESTAMP
);
ALTER TABLE ARTICLE_COMMENT ADD CONSTRAINT ARTI_COMM_PK PRIMARY KEY (ID);
ALTER TABLE ARTICLE_COMMENT ADD CONSTRAINT ARTI_COMM_ARTI_FK_1 FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ID);
ALTER TABLE ARTICLE_COMMENT ADD CONSTRAINT ARTI_COMM_ARTI_COMM_STAT_FK_1 FOREIGN KEY (STATUS_ID) REFERENCES ARTICLE_COMMENT_STATUS (ID);
ALTER TABLE ARTICLE_COMMENT ADD CONSTRAINT ARTI_COMM_USER_FK_1 FOREIGN KEY (UC) REFERENCES USERS (ID);
ALTER TABLE ARTICLE_COMMENT ADD CONSTRAINT ARTI_COMM_USER_FK_2 FOREIGN KEY (UM) REFERENCES USERS (ID);
ALTER TABLE ARTICLE_COMMENT ADD CONSTRAINT ARTI_COMM_USER_FK_3 FOREIGN KEY (PUBLISHED_BY) REFERENCES USERS (ID);

-- ARTICLE_BOOKMARK
CREATE TABLE ARTICLE_BOOKMARK (
  ID         INTEGER   NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ARTICLE_ID INTEGER   NOT NULL,
  UC         INTEGER   NOT NULL,
  DC         TIMESTAMP NOT NULL,
  UM         INTEGER,
  DM         TIMESTAMP
);
ALTER TABLE ARTICLE_BOOKMARK ADD CONSTRAINT ARTI_BOOK_PK PRIMARY KEY (ID);
ALTER TABLE ARTICLE_BOOKMARK ADD CONSTRAINT ARTI_BOOK_UK_1 UNIQUE (UC, ARTICLE_ID);
ALTER TABLE ARTICLE_BOOKMARK ADD CONSTRAINT ARTI_BOOK_ARTI_FK_1 FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ID);
ALTER TABLE ARTICLE_BOOKMARK ADD CONSTRAINT ARTI_BOOK_USER_FK_1 FOREIGN KEY (UC) REFERENCES USERS (ID);
ALTER TABLE ARTICLE_BOOKMARK ADD CONSTRAINT ARTI_BOOK_USER_FK_2 FOREIGN KEY (UM) REFERENCES USERS (ID);
