-- ROLES
CREATE TABLE ROLES (
  ID   INTEGER      NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CD   VARCHAR (15) NOT NULL,
  NAME VARCHAR (50) NOT NULL
);
ALTER TABLE ROLES ADD CONSTRAINT ROLE_PK PRIMARY KEY (ID);
ALTER TABLE ROLES ADD CONSTRAINT ROLE_UK_1 UNIQUE (CD);

-- COUNTRY
CREATE TABLE COUNTRY (
  ID   INTEGER      NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CD   VARCHAR (15) NOT NULL,
  NAME VARCHAR (50) NOT NULL
);
ALTER TABLE COUNTRY ADD CONSTRAINT COUN_PK PRIMARY KEY (ID);
ALTER TABLE COUNTRY ADD CONSTRAINT COUN_UK_1 UNIQUE (CD);

-- ADDRESS
CREATE TABLE ADDRESS (
  ID           INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  EMAIL        VARCHAR (100),
  PHONE        VARCHAR (50),
  STREET_LINE  VARCHAR (100),
  CITY         VARCHAR (50),
  POSTAL_CODE  VARCHAR (15),
  COUNTRY      VARCHAR (50),
  COUNTRY_CODE VARCHAR (15),
  WWW          VARCHAR (250)
);
ALTER TABLE ADDRESS ADD CONSTRAINT ADDR_PK PRIMARY KEY (ID);

-- USER_STATUS
CREATE TABLE USER_STATUS ( 
  ID INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
  CD VARCHAR (15)   NOT NULL, 
  NAME VARCHAR (50) NOT NULL 
);
ALTER TABLE USER_STATUS ADD CONSTRAINT USER_STAT_PK PRIMARY KEY (ID);
ALTER TABLE USER_STATUS ADD CONSTRAINT USER_STAT_UK_1 UNIQUE (CD);

-- USERS
CREATE TABLE USERS (
  ID                 INTEGER         NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  USER_NAME          VARCHAR (50)    NOT NULL,
  PASSWORD           VARCHAR (250)   NOT NULL,
  STATUS_ID          INTEGER         NOT NULL,
  ROLE_ID            INTEGER         NOT NULL,
  FIRST_NAME         VARCHAR (50),
  LAST_NAME          VARCHAR (50),
  BIRTHDATE          DATE,
  IMAGE BLOB,
  IMAGE_CONTENT_TYPE VARCHAR (100),
  ADDRESS_ID INTEGER
);
ALTER TABLE USERS ADD CONSTRAINT USER_PK PRIMARY KEY (ID);
ALTER TABLE USERS ADD CONSTRAINT USER_UK_1 UNIQUE (USER_NAME);
ALTER TABLE USERS ADD CONSTRAINT USER_ROLE_FK_1 FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID);
ALTER TABLE USERS ADD CONSTRAINT USER_USER_STAT_FK_1 FOREIGN KEY (STATUS_ID) REFERENCES USER_STATUS (ID);
ALTER TABLE USERS ADD CONSTRAINT USER_ADDR_FK_1 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID);
