-- MARKETING
DELETE FROM AD_ARTICLE;
DELETE FROM AD;
DELETE FROM AD_STATUS;
DELETE FROM ADVERTISER;

-- MAGAZINE
DELETE FROM ARTICLE_CATEGORY;
DELETE FROM ARTICLE_STATUS;
DELETE FROM ARTICLE;
DELETE FROM CATEGORY;
DELETE FROM READER_TYPE;
DELETE FROM ARTICLE_BOOKMARK;
DELETE FROM ARTICLE_COMMENT;
DELETE FROM ARTICLE_COMMENT_STATUS;
DELETE FROM ARTICLE_RATE;

-- CONTENT MANAGEMENT
DELETE FROM CONTENT;
DELETE FROM CONTENT_TYPE;
DELETE FROM MANAGED_CONTENT;

-- PROJECT MANAGEMENT
DELETE FROM TASK_COMMENT;
DELETE FROM TASK_ATTACHMENT;
DELETE FROM TASK_STATUS;
DELETE FROM TASK_PRIORITY;
DELETE FROM TASK;

-- SYSTEM
DELETE FROM USERS;
DELETE FROM USER_STATUS;
DELETE FROM ADDRESS;
DELETE FROM COUNTRY;
DELETE FROM ROLES;