-- CUSTOMER CARE
DROP TABLE AD;
DROP TABLE CUSTOMER;

-- SOCIAL NETWORKING
DROP TABLE ARTICLE_BOOKMARK;
DROP TABLE ARTICLE_COMMENT;
DROP TABLE ARTICLE_COMMENT_STATUS;
DROP TABLE ARTICLE_RATE;
DROP TABLE USER_ARTICLE;
DROP TABLE USER_ARTICLE_STATUS;

-- MAGAZINE
DROP TABLE ARTICLE_CATEGORY;
DROP TABLE ARTICLE_STATUS;
DROP TABLE ARTICLE;
DROP TABLE CATEGORY;
DROP TABLE READER_TYPE;

-- CONTENT MANAGEMENT
DROP TABLE CONTENT;
DROP TABLE CONTENT_TYPE;
DROP TABLE MANAGED_CONTENT;

-- PROJECT MANAGEMENT
DROP TABLE TASK_COMMENT;
DROP TABLE TASK_ATTACHMENT;
DROP TABLE TASK_STATUS;
DROP TABLE TASK_PRIORITY;
DROP TABLE TASK;

-- SYSTEM
DROP TABLE USERS;
DROP TABLE USER_STATUS;
DROP TABLE ADDRESS;
DROP TABLE COUNTRY;
DROP TABLE ROLES;